/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershopsystem;

import java.util.Calendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author scollex
 */
public class AddOrder1 extends javax.swing.JFrame {

    /**
     * Creates new form AddOrder1
     */
    ProductOrder[] prodOrder = new ProductOrder[50];
    int count = 0;
    public DefaultTableModel dm;

    public AddOrder1() {
        initComponents();
        loadDataIntoDDL();
    }

    public AddOrder1(int id) {
        initComponents();
        setupData(id);
        loadDataIntoDDL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMakeOrder = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDelivery = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        jUpdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();
        jSubTotal = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProduct = new javax.swing.JComboBox<String>();
        jAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPickUpMinute = new javax.swing.JComboBox<String>();
        jPickUpHour = new javax.swing.JComboBox<String>();
        jAddPanel = new javax.swing.JPanel();
        jAddUnit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jAddCity = new javax.swing.JTextField();
        jAddState = new javax.swing.JTextField();
        jAddPostcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAddStreet = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        CustType = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCML = new javax.swing.JTextField();
        jCopName = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMakeOrder.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jMakeOrder.setText("Make Order");
        jMakeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMakeOrderActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setText("Delivery Method :");

        jDelivery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pick Up", "Delivery" }));
        jDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeliveryActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Please choose Your Preference Delivery Method");

        jUpdate.setText("Update");
        jUpdate.setEnabled(false);
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SubTotal : ");

        jDelete.setText("Delete");
        jDelete.setEnabled(false);
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSubTotal.setText("0");

        jAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountActionPerformed(evt);
            }
        });

        jStock.setEnabled(false);
        jStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStockActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Amount");

        jPrice.setEnabled(false);
        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Total :");

        jTotal.setEnabled(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Unit Price", "Amount", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Product : ");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("In Stock");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Price :");

        jProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProductActionPerformed(evt);
            }
        });

        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton2.setText("Cancel");

        jCancel.setVisible(false);
        jCancel.setText("Cancel");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jPanel1.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Date :");

        jLabel20.setText(":");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Time : ");

        jPickUpMinute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45" }));
        jPickUpMinute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickUpMinuteActionPerformed(evt);
            }
        });

        jPickUpHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        jPickUpHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPickUpHourActionPerformed(evt);
            }
        });

        jAddUnit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address");

        jAddCity.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jAddState.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jAddPostcode.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("No / Unit");

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Street / Jalan");

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("State");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("City");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Postcode");

        jAddStreet.setColumns(20);
        jAddStreet.setRows(5);
        jScrollPane2.setViewportView(jAddStreet);

        javax.swing.GroupLayout jAddPanelLayout = new javax.swing.GroupLayout(jAddPanel);
        jAddPanel.setLayout(jAddPanelLayout);
        jAddPanelLayout.setHorizontalGroup(
            jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAddCity, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jAddUnit)
                    .addComponent(jAddPostcode)
                    .addComponent(jAddState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                .addContainerGap())
        );
        jAddPanelLayout.setVerticalGroup(
            jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAddPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAddPanelLayout.createSequentialGroup()
                        .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jAddState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPickUpHour, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPickUpMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPickUpHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jPickUpMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CustType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Consumer", "Coorperate Customer" }));
        CustType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustTypeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Current Credit Limit :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Please Select Customer Type");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Name : ");

        jCML.setEnabled(false);
        jCML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCMLActionPerformed(evt);
            }
        });

        jCopName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCopNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCopName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(CustType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCML, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jMakeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel14)
                            .addGap(1, 1, 1)
                            .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAdd)
                                .addGap(19, 19, 19)
                                .addComponent(jUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(jDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jStock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMakeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jAdd)
                                    .addComponent(jUpdate)
                                    .addComponent(jDelete)
                                    .addComponent(jCancel))
                                .addGap(28, 28, 28)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMakeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMakeOrderActionPerformed
        // TODO add your handling code here:
        saveintoOrderList();
    }//GEN-LAST:event_jMakeOrderActionPerformed

    private void saveintoOrderList() {
        String custName = jCopName.getSelectedItem().toString();
        int delivery_year = jDate.getCalendar().get(Calendar.YEAR);
        int delivery_month = jDate.getCalendar().get(Calendar.MONTH);
        int delivery_day = jDate.getCalendar().get(Calendar.DAY_OF_MONTH);
        int pickHour = Integer.parseInt(jPickUpHour.getSelectedItem().toString());
        int pickMinute = Integer.parseInt(jPickUpMinute.getSelectedItem().toString());
        Calendar processDay = Calendar.getInstance();
        processDay.add(Calendar.DAY_OF_MONTH, 3);
        Calendar orderDate = Calendar.getInstance();
        Calendar deliDate = Calendar.getInstance();
        deliDate.set(Calendar.YEAR, delivery_year);
        deliDate.set(Calendar.MONTH, delivery_month);
        deliDate.set(Calendar.DAY_OF_MONTH, delivery_day);
        deliDate.set(Calendar.HOUR_OF_DAY, pickHour);
        deliDate.set(Calendar.MINUTE, pickMinute);

        OrderDetails order = null;
        if (orderDate.before(Calendar.getInstance())) {
            JOptionPane.showMessageDialog(this, "Date invalid!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (orderDate.after(processDay)) {
            JOptionPane.showMessageDialog(this, "Order must be 3 days prior", "Date Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int i = 0; i < MainMenu.custList.size(); i++) {
            if (MainMenu.custList.get(i).name.equalsIgnoreCase(custName)) {
                order = new OrderDetails(MainMenu.custList.get(i), orderDate,
                        Float.parseFloat(jSubTotal.getText()),
                        prodOrder);
                if (jDelivery.getSelectedItem().toString().equalsIgnoreCase("Delivery")) {
                    String unit = jAddUnit.getText();
                    String street = jAddStreet.getText();
                    String city = jAddCity.getText();
                    String state = jAddState.getText();
                    String country = "Malaysia";
                    int postcode = Integer.parseInt(jAddPostcode.getText());

                    Delivery deli = new Delivery(deliDate,
                            new Delivery.Address(unit, street, city, state, country, postcode),
                            order);
                    MainMenu.retrieving.enqueue(deli);
                } else {
                    MainMenu.retrieving.enqueue(new PickUp(deliDate, order));
                }

            }
            this.dispose();
            JOptionPane.showMessageDialog(this, "Your Order Are Made Successfully", "Order Successful", JOptionPane.INFORMATION_MESSAGE);

        }
    }

    private void jPickUpMinuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickUpMinuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPickUpMinuteActionPerformed

    private void jPickUpHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPickUpHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPickUpHourActionPerformed

    private void jDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeliveryActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        if (jDelivery.getSelectedIndex() == 0) {
            jLabel7.setVisible(true);
            jDate.setVisible(true);
            jLabel8.setVisible(false);
            jAddPanel.setVisible(false);
            jLabel10.setVisible(true);
            jPickUpHour.setVisible(true);
        }
        if (jDelivery.getSelectedIndex() == 1) {
            jLabel8.setVisible(true);
            jAddPanel.setVisible(true);

        }
    }//GEN-LAST:event_jDeliveryActionPerformed

    private void jCopNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCopNameActionPerformed
        String usercurrentLimit = (String) jCopName.getSelectedItem();

        if (CustType.getSelectedIndex() == 2) {
            for (int i = 0; i < MainMenu.custList.size(); i++) {
                if (MainMenu.custList.get(i).name.equalsIgnoreCase(usercurrentLimit)) {
                    jCML.setText(String.valueOf(MainMenu.custList.get(i).currentLimit));
                    System.out.println(usercurrentLimit);
                    System.out.println(MainMenu.custList.get(i).currentLimit);
                }
            }
        }
    }//GEN-LAST:event_jCopNameActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String pName = jProduct.getSelectedItem().toString();
            int stock = Integer.parseInt(jStock.getText());
            double pTotal = Double.parseDouble(jTotal.getText());
            float unitPrice = Float.parseFloat(jPrice.getText());
            int pQuantity = Integer.parseInt(jAmount.getText());
            TableModel model = jTable1.getModel();
            int index = jTable1.getSelectedRow();

            prodOrder[index].pAmount = pQuantity;
            prodOrder[index].pTotal = pTotal;
            prodOrder[index].p.amt = stock - pQuantity;
            JOptionPane.showMessageDialog(this, "Record Updated!");
            model.setValueAt(pQuantity, index, 2);
            model.setValueAt(pTotal, index, 3);
            JOptionPane.showMessageDialog(this, "Item added");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid input!", "Input format error", JOptionPane.ERROR_MESSAGE);
        } finally {
            calculateSubtotal();
        }

        jUpdate.setEnabled(false);
        jDelete.setEnabled(false);
        jProduct.setSelectedItem(null);
        jStock.setText(null);
        jAmount.setText(null);
        jPrice.setText(null);
        jTotal.setText(null);
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        try {
            dm = (DefaultTableModel) jTable1.getModel();
            int index = jTable1.getSelectedRow();
            if (count == 1 || index == count - 1) {
                prodOrder[index] = null;
            } else {
                ProductOrder[] tempArr = new ProductOrder[50];
                for (int i = 0, j = 0; j < jTable1.getRowCount(); i++, j++) {
                    if (i != index) {
                        tempArr[i] = prodOrder[j];
                        System.out.println("tempArr: " + tempArr[i].toString());
                        System.out.println("prodOrder: " + prodOrder[i].toString());
                    } else {
                        j++;
                        tempArr[i] = prodOrder[j];
                        System.out.println("tempArr: " + tempArr[i].toString());
                        System.out.println("prodOrder: " + prodOrder[i].toString());
                    }
                }
                prodOrder = tempArr;
            }
            count--;
            dm.removeRow(index);

            MainMenu.prodList.remove(index);
            calculateSubtotal();

            JOptionPane.showMessageDialog(this, "Deleted Success");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Delete Uncessful", "Delete Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        }
        jUpdate.setEnabled(false);
        jDelete.setEnabled(false);
        jCancel.setVisible(false);
        jAdd.setVisible(true);
        jProduct.setSelectedItem(null);
        jStock.setText(null);
        jAmount.setText(null);
        jPrice.setText(null);
        jTotal.setText(null);
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountActionPerformed
        try {
            jTotal.setText(String.valueOf(Integer.parseInt(jAmount.getText())
                    * Float.parseFloat(jPrice.getText())));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid input", "Input format error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jAmountActionPerformed

    private void jStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStockActionPerformed

    }//GEN-LAST:event_jStockActionPerformed

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriceActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed

    }//GEN-LAST:event_jTotalActionPerformed

    private void CustTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustTypeActionPerformed

        jCopName.removeAllItems();
        if (CustType.getSelectedIndex() == 1) {
            jLabel9.setVisible(false);
            jCML.setVisible(false);
            jLabel11.setVisible(true);
            jCopName.setVisible(true);
            for (int i = 0; i < MainMenu.custList.size(); i++) {
                if (MainMenu.custList.get(i).custType.equalsIgnoreCase("Consumer")) {
                    jCopName.addItem(MainMenu.custList.get(i).name);
                }
            }
        }
        if (CustType.getSelectedIndex() == 2) {
            jLabel9.setVisible(true);
            jCML.setVisible(true);
            jLabel11.setVisible(true);
            jCopName.setVisible(true);
            for (int i = 0; i < MainMenu.custList.size(); i++) {
                if (MainMenu.custList.get(i).custType.equalsIgnoreCase("Corporate Customer")) {
                    jCopName.addItem(MainMenu.custList.get(i).name);
                }
            }
        }
    }//GEN-LAST:event_CustTypeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jAdd.setVisible(false);
        jCancel.setVisible(true);
        jUpdate.setEnabled(true);
        jDelete.setEnabled(true);

        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();

        String pName = prodOrder[index].p.name;
        String pUnitPrice = String.valueOf(prodOrder[index].p.price);
        String pAmt = String.valueOf(prodOrder[index].pAmount);
        String pTotal = String.valueOf(prodOrder[index].pTotal);
        String stock = String.valueOf(prodOrder[index].p.amt + prodOrder[index].pAmount);

        if (pAmt.equals("")) {
            jProduct.setSelectedIndex(0);
        }

        jProduct.setSelectedItem(pName);
        jPrice.setText(pUnitPrice);
        jAmount.setText(pAmt);
        jStock.setText(stock);
        jTotal.setText(pTotal);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProductActionPerformed
        String product = (String) jProduct.getSelectedItem();

        for (int i = 0; i < MainMenu.prodList.size(); i++) {
            if (MainMenu.prodList.get(i).name.equalsIgnoreCase(product)) {
                jStock.setText(String.valueOf(MainMenu.prodList.get(i).amt));
                jPrice.setText(String.valueOf(MainMenu.prodList.get(i).price));
            }
        }

    }//GEN-LAST:event_jProductActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // TODO add your handling code here:
        addProductOrder();

        dm = (DefaultTableModel) jTable1.getModel();
        int pQuantity = Integer.parseInt(jAmount.getText());
        float pPrice = Float.parseFloat(jPrice.getText());
        try {
            Object[] data = {jProduct.getSelectedItem(), pPrice, pQuantity, jTotal.getText()};
            dm.addRow(data);
            JOptionPane.showMessageDialog(this, "Item added");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Data input error", "Input Unsuccesfull", JOptionPane.ERROR_MESSAGE);
        } finally {
            loadDataIntoDDL();
            calculateSubtotal();
        }
        jProduct.setSelectedIndex(0);
        jStock.setText(null);
        jAmount.setText(null);
        jPrice.setText(null);
        jTotal.setText(null);
    }//GEN-LAST:event_jAddActionPerformed

    private void jCMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCMLActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
        jTable1.clearSelection();
        jUpdate.setEnabled(false);
        jDelete.setEnabled(false);
        jProduct.setSelectedItem(null);
        jStock.setText(null);
        jAmount.setText(null);
        jPrice.setText(null);
        jTotal.setText(null);
        jCancel.setVisible(false);
        jAdd.setVisible(true);
    }//GEN-LAST:event_jCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CustType;
    private javax.swing.JButton jAdd;
    private javax.swing.JTextField jAddCity;
    private javax.swing.JPanel jAddPanel;
    private javax.swing.JTextField jAddPostcode;
    private javax.swing.JTextField jAddState;
    private javax.swing.JTextArea jAddStreet;
    private javax.swing.JTextField jAddUnit;
    private javax.swing.JTextField jAmount;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCML;
    private javax.swing.JButton jCancel;
    private javax.swing.JComboBox<String> jCopName;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JButton jDelete;
    private javax.swing.JComboBox<String> jDelivery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jMakeOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jPickUpHour;
    private javax.swing.JComboBox<String> jPickUpMinute;
    private javax.swing.JTextField jPrice;
    private javax.swing.JComboBox<String> jProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jStock;
    private javax.swing.JLabel jSubTotal;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables

    private void loadDataIntoDDL() {
        jProduct.removeAllItems();
        jProduct.addItem(" ");
        jCopName.removeAll();
        jCopName.addItem(" ");
        for (Product prodList : MainMenu.prodList) {
            jProduct.addItem(prodList.getName());
        }
    }

    private void addProductOrder() {
        try {
            String name = (String) jProduct.getSelectedItem();
            System.out.println("name" + name);
            int stock = Integer.parseInt(jStock.getText());
            int amt = Integer.parseInt(jAmount.getText());
            System.out.println("Amount:" + amt);
            float unitPrice = Float.parseFloat(jPrice.getText());
            Product p = new Product(name, stock, unitPrice);
            prodOrder[count] = new ProductOrder(p, amt);
            System.out.println("New prodOrder: " + prodOrder[count].toString());
            updateProdList(p, amt);
            count++;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid input", "Input format error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void updateProdList(Product p, int amt) {
        for (Product prod : MainMenu.prodList) {
            if (prod.getName().equalsIgnoreCase(p.getName())) {
                prod.amt -= amt;
            }
        }
    }

    private void calculateSubtotal() {
        float subtotal = (float) 0.000;
        for (int i = 0; i < count; i++) {
            subtotal += prodOrder[i].pTotal;
        }
        jSubTotal.setText(String.valueOf(subtotal));
    }

    private void setupData(int id) {
        int index = 0;
        while (!MainMenu.retrieving.IsEmpty()) {
            index++;
            //loop trough the list the look for a match
            if (MainMenu.retrieving.get(index).order.orderid == id) {
                //break the loop if match found
                break;
            }
        }
        //Retrieve the data using get(index), where index are found previously
        //and store into a temporaly class
        Retrieval r = MainMenu.retrieving.get(index);
        dm = (DefaultTableModel) jTable1.getModel();
        for (ProductOrder order : r.order.product) {
            Object[] data = {order.p.name, order.p.price, order.pAmount, order.pTotal};
            dm.addRow(data);
        }
        CustType.removeAllItems();
        CustType.addItem(r.order.cust.custType);
        if (r.order.cust.custType.equalsIgnoreCase("consumer")) {
            jLabel9.setVisible(false);
            jCML.setVisible(false);
        } else {
            jCML.setText(String.valueOf(r.order.cust.currentLimit));
        }
        jCopName.addItem(r.order.cust.name);
        jDelivery.removeAllItems();;
        if (r instanceof Delivery) {
            jDelivery.addItem("Delivery");
            jAddPanel.setVisible(true);
            jAddUnit.setText(r.add.unit);
            jAddStreet.setText(r.add.street);
            jAddState.setText(r.add.state);
            jAddPostcode.setText(String.valueOf(r.add.postcode));
            jAddCity.setText(r.add.city);
        } else {
            jDelivery.addItem("Pick Up");
            jAddPanel.setVisible(false);
        }
        jDate.setCalendar(r.Date_Of_Agree);
        int hour = r.Date_Of_Agree.get(Calendar.HOUR_OF_DAY);
        int min = r.Date_Of_Agree.get(Calendar.MINUTE);
        jPickUpHour.setSelectedIndex(hour - 9);
        jPickUpMinute.setSelectedIndex(0);
    }
}
