/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershopsystem;

import static flowershopsystem.MainMenu.customizeList;
import static flowershopsystem.MainMenu.prodList;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LIANG
 */
public class CustomizeOrder extends javax.swing.JFrame {

    public DefaultTableModel dm;
    OrderDetails order;

    /**
     * Creates new form Customize
     */
    public CustomizeOrder() {
        initComponents();
        loadDataIntoDDL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jAccessories = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jSizePrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFlowerPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jAddOnPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jStyle = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSize = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFlowerType = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPriority = new javax.swing.JComboBox<String>();
        CustPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        jCustName = new javax.swing.JComboBox<String>();
        jMakeCustomize = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Customize Flower");

        jAccessories.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Ferrero Rocher", "Teddy Bear" }));
        jAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccessoriesActionPerformed(evt);
            }
        });

        jLabel11.setText("Price (RM) : ");

        jSizePrice.setEnabled(false);
        jSizePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizePriceActionPerformed(evt);
            }
        });

        jLabel12.setText("Price (RM) : ");

        jFlowerPrice.setEnabled(false);

        jLabel13.setText("Price (RM) : ");

        jAddOnPrice.setEnabled(false);
        jAddOnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddOnPriceActionPerformed(evt);
            }
        });

        jLabel2.setText("Arrangement Style : ");

        jStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "White Christmas", "Forest Green", "12 Red Roses Korean Style", "Jade" }));

        jLabel3.setText("Arrangement Size : ");

        jLabel16.setText("Total (RM) :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Step 1: Select Your Arrangement Style");

        jTotal.setEnabled(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Step 2 : Select the size that you wanted");

        jSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Big", "Small" }));
        jSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Step 3 : Select the flower type ");

        jLabel7.setText("Flower Type :");

        jFlowerType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Rose", "Sunflower", "" }));
        jFlowerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFlowerTypeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Step 4 : Add On Accessories");

        jLabel10.setText("Add On Accessories : ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Step 5 : Select Your Priority ");

        jPriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choos a priority", "Express", "Standard" }));
        jPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriorityActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Step 6: Please Select Customer");

        lblCustName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblCustName.setText("Name : ");

        jCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustPanelLayout = new javax.swing.GroupLayout(CustPanel);
        CustPanel.setLayout(CustPanelLayout);
        CustPanelLayout.setHorizontalGroup(
            CustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustPanelLayout.createSequentialGroup()
                        .addComponent(lblCustName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        CustPanelLayout.setVerticalGroup(
            CustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustPanelLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CustPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jAddOnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSizePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFlowerType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFlowerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(21, 21, 21)
                        .addComponent(jPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jSizePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFlowerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jFlowerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jAddOnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(CustPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMakeCustomize.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMakeCustomize.setText("Make Customize Order");
        jMakeCustomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMakeCustomizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMakeCustomize)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jMakeCustomize)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTotalActionPerformed

    private void jSizePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizePriceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSizePriceActionPerformed

    private void jSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizeActionPerformed
        // TODO add your handling code here:
        if (jSize.getSelectedIndex() == 1) {
            jSizePrice.setText("55");
        } else if (jSize.getSelectedIndex() == 2) {
            jSizePrice.setText("30");
        }
    }//GEN-LAST:event_jSizeActionPerformed

    private void jFlowerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFlowerTypeActionPerformed
        // TODO add your handling code here:
        switch (jFlowerType.getSelectedIndex()) {
            case 1:
                jFlowerPrice.setText("20");
                break;
            case 2:
                jFlowerPrice.setText("25");
                break;
            case 3:
                jFlowerPrice.setText("11");
                break;
            case 4:
                jFlowerPrice.setText("16");
                break;
            default:
                break;
        }

    }//GEN-LAST:event_jFlowerTypeActionPerformed

    private void jAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccessoriesActionPerformed
        if (jAccessories.getSelectedIndex() == 1) {
            jAddOnPrice.setText("40");
            calculateTotal();
        } else if (jAccessories.getSelectedIndex() == 2) {
            jAddOnPrice.setText("25");
            calculateTotal();
        }

    }//GEN-LAST:event_jAccessoriesActionPerformed

    private void jAddOnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddOnPriceActionPerformed

    }//GEN-LAST:event_jAddOnPriceActionPerformed

    private void jMakeCustomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMakeCustomizeActionPerformed
        // TODO add your handling code here:
        CustomizeFlower customize = null;
        try {
            String flowerArrangementName = jStyle.getSelectedItem().toString();
            String ArrangementSize = jSize.getSelectedItem().toString();
            String flowertype = jFlowerType.getSelectedItem().toString();
            String accessories = jAccessories.getSelectedItem().toString();
            String priority = jPriority.getSelectedItem().toString();
            float price = Float.parseFloat(jTotal.getText());
            String custName = jCustName.getSelectedItem().toString();
            Customer c = null;

            for (int i = 0; i < MainMenu.custList.size(); i++) {
                if (MainMenu.custList.get(i).getName().equalsIgnoreCase(custName)) {
                    c = MainMenu.custList.get(i);
                }
            }

            customize = new CustomizeFlower(
                    flowerArrangementName, ArrangementSize, flowertype, accessories,
                    priority, price, c);

            if (jPriority.getSelectedItem().toString().equalsIgnoreCase("EXPRESS")) {
                MainMenu.customizeList.enqueueFront(customize);
            } else {
                MainMenu.customizeList.enqueue(customize);
            }

            JOptionPane.showMessageDialog(this, "Customize Order added");
            this.dispose();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Data input error", "Input Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMakeCustomizeActionPerformed

    private void jCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustNameActionPerformed
        // TODO add your handling code here:
        if (jCustName.getSelectedIndex() == 1 || jCustName.getSelectedIndex() == 2) {
            jMakeCustomize.setVisible(true);
        }
    }//GEN-LAST:event_jCustNameActionPerformed

    private void jPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriorityActionPerformed
        // TODO add your handling code here:
        if (jPriority.getSelectedIndex() == 1 || jPriority.getSelectedIndex() == 2) {
            jMakeCustomize.setVisible(true);
        }
    }//GEN-LAST:event_jPriorityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomizeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomizeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomizeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomizeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomizeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustPanel;
    private javax.swing.JComboBox<String> jAccessories;
    private javax.swing.JTextField jAddOnPrice;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jCustName;
    private javax.swing.JTextField jFlowerPrice;
    private javax.swing.JComboBox<String> jFlowerType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jMakeCustomize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jPriority;
    private javax.swing.JComboBox<String> jSize;
    private javax.swing.JTextField jSizePrice;
    private javax.swing.JComboBox<String> jStyle;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JLabel lblCustName;
    // End of variables declaration//GEN-END:variables

    private void loadDataIntoDDL() {
        jFlowerType.removeAllItems();
        jCustName.removeAllItems();
        jFlowerType.addItem(" ");
        jCustName.addItem("Choose a customer");
        for (int i = 0; i < MainMenu.prodList.size(); i++) {
            jFlowerType.addItem(MainMenu.prodList.get(i).getName());
        }
        for (int i = 0; i < MainMenu.custList.size(); i++) {
            if (MainMenu.custList.get(i).getCustType().equalsIgnoreCase("CONSUMER")) {
                jCustName.addItem(MainMenu.custList.get(i).getName());
            }
        }
    }

    private void calculateTotal() {
        try {
            float sizeprice = Float.parseFloat(jSizePrice.getText());
            float flowerprice = Float.parseFloat(jFlowerPrice.getText());
            float addOnprice = Float.parseFloat(jAddOnPrice.getText());

            String total = String.valueOf(sizeprice + flowerprice + addOnprice);
            jTotal.setText(total);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Data input incomplete", "Input Unsuccessful", JOptionPane.ERROR_MESSAGE);
            jAccessories.setSelectedIndex(0);
        }
    }
}
