/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershopsystem;

import static flowershopsystem.MainMenu.customizeList;
import static flowershopsystem.MainMenu.prodList;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LIANG
 */
public class Customize extends javax.swing.JFrame {

    public DefaultTableModel dm;

    /**
     * Creates new form Customize
     */
    public Customize() {
        initComponents();
        loadDataIntoDDL();
        loadDataIntoTable();
    }

    private void loadDataIntoTable() {
        dm = (DefaultTableModel) jTable1.getModel();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        CustomizeListInterface<CustomizeFlower> clist = new CustomizeLinkedList<>();
        while (!MainMenu.customizeList.isEmpty()) {
            CustomizeFlower c = MainMenu.customizeList.dequeue();

            Object[] data = {c.id, c.flowerArrangementName, c.ArrangementSize, c.flowertype, c.accessories,
                c.priority, c.price, format.format(c.customizeDate.getTime())};
            dm.addRow(data);
            System.out.println("c: ");
            System.out.println(c.ArrangementSize);
            System.out.println(c.accessories);
            clist.enqueue(c);
        }
        MainMenu.customizeList = clist;

        /*for (int i = 0; i < MainMenu.customizeList; i++) {
            Object[] data = {MainMenu.customizeList.get(i).id, MainMenu.customizeList.get(i).flowerArrangementName,
                MainMenu.customizeList.get(i).ArrangementSize, MainMenu.customizeList.get(i).flowertype,
                MainMenu.customizeList.get(i).accessories, MainMenu.customizeList.get(i).price,
                MainMenu.customizeList.get(i).priority};
            dm.addRow(data);

        } */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jStyle = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSize = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFlowerType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jAccessories = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSizePrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFlowerPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jAddOnPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSubTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPriority = new javax.swing.JComboBox<>();
        jAddCustomize = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jUpdate = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCusDate = new com.toedter.calendar.JDateChooser();

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customize Flower");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Style", "Size", "Flower Type", "Accessories", "Priority", "Total", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Arrangement Style : ");

        jStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "White Christmas", "Forest Green", "12 Red Roses Korean Style", "Jade" }));

        jLabel3.setText("Arrangement Size : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Step 1: Select Your Arrangement Style");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Step 2 : Select the size that you wanted");

        jSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Big", "Small" }));
        jSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Step 3 : Select the flower type ");

        jLabel7.setText("Flower Type :");

        jFlowerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Rose", "Sunflower", "" }));
        jFlowerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFlowerTypeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Step 4 : Add On Accessories");

        jLabel10.setText("Add On Accessories : ");

        jAccessories.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ferrero Rocher", "Teddy Bear" }));
        jAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAccessoriesActionPerformed(evt);
            }
        });

        jLabel11.setText("Price (RM) : ");

        jSizePrice.setEnabled(false);
        jSizePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizePriceActionPerformed(evt);
            }
        });

        jLabel12.setText("Price (RM) : ");

        jFlowerPrice.setEnabled(false);

        jLabel13.setText("Price (RM) : ");

        jAddOnPrice.setEnabled(false);
        jAddOnPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddOnPriceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SubTotal  (RM) : ");

        jSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSubTotal.setText("0");
        jSubTotal.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Step 5 : Select Your Priority ");

        jPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Express", "Normal", "Flexible" }));
        jPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriorityActionPerformed(evt);
            }
        });

        jAddCustomize.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAddCustomize.setText("Add Customize");
        jAddCustomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddCustomizeActionPerformed(evt);
            }
        });

        jDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDelete.setText("Delete Customize");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jLabel16.setText("Total (RM) :");

        jTotal.setEnabled(false);
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jUpdate.setText("Update Customize");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Step 6 : Select Your Order Date ");

        jLabel9.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSizePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFlowerType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFlowerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jAddOnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jPriority, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jAddCustomize)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jUpdate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jDelete))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel15))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addComponent(jCusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jSizePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jFlowerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jFlowerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jAccessories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jAddOnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jAddCustomize)
                                    .addComponent(jDelete)
                                    .addComponent(jUpdate))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddCustomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddCustomizeActionPerformed

        String id = saveCustomizeIntoArray();
        dm = (DefaultTableModel) jTable1.getModel();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        CustomizeListInterface<CustomizeFlower> clist = new CustomizeLinkedList<>();
            try {
                {
                    Object[] data = {id, jStyle.getSelectedItem().toString(), jSize.getSelectedItem().toString(), jFlowerType.getSelectedItem().toString(), jAccessories.getSelectedItem().toString(), jPriority.getSelectedItem().toString(), jTotal.getText(), format.format(jCusDate.getCalendar().getTime())};
                    ;
                    dm.addRow(data);
                }
                calculateSubTotal();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Data input error", "Input Unsuccesfull", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jAddCustomizeActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        try {
            dm = (DefaultTableModel) jTable1.getModel();
            int index = jTable1.getSelectedRow();

            String customizename = jStyle.getSelectedItem().toString();
            String customizeSize = jSize.getSelectedItem().toString();
            String customizeType = jFlowerType.getSelectedItem().toString();
            String customizeAccesories = jAccessories.getSelectedItem().toString();
            String customizePriority = jPriority.getSelectedItem().toString();
            float Total = Float.parseFloat(jTotal.getText());
            int customize_year = jCusDate.getCalendar().get(Calendar.YEAR);
            int customize_month = jCusDate.getCalendar().get(Calendar.MONTH);
            int customize_day = jCusDate.getCalendar().get(Calendar.DAY_OF_MONTH);

            Calendar customizeDate = Calendar.getInstance();
            customizeDate.set(Calendar.YEAR, customize_year);
            customizeDate.set(Calendar.MONTH, customize_month);
            customizeDate.set(Calendar.MONTH, customize_day);

            CustomizeFlower customize = new CustomizeFlower(customizename, customizeSize, customizeType, customizeAccesories, (float) Total, customizePriority, customizeDate);

            dm.removeRow(index);

            MainMenu.customizeList.dequeue();
            calculateSubTotal();
            JOptionPane.showMessageDialog(this, "Customize Order have been deleted successfully.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Delete Unsuccessful", "Delete Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
        jDelete.setEnabled(false);

    }//GEN-LAST:event_jDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jAddCustomize.setEnabled(false);
        jDelete.setEnabled(true);
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String id = (String) jTable1.getValueAt(index, 0);
        new CustomizeConfirm(id).setVisible(true);
        
        String customizename = model.getValueAt(index, 1).toString();
        String customizeSize = model.getValueAt(index, 2).toString();
        String customizeType = model.getValueAt(index, 3).toString();
        String customizeAccesories = model.getValueAt(index, 4).toString();
        String customizePriority = model.getValueAt(index, 5).toString();

        jStyle.setSelectedItem(customizename);
        jSize.setSelectedItem(customizeSize);
        jFlowerType.setSelectedItem(customizeType);
        jAccessories.setSelectedItem(customizeAccesories);
        jPriority.setSelectedItem(customizePriority);
        jAddCustomize.setEnabled(false);


    }//GEN-LAST:event_jTable1MouseClicked

    private void jPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriorityActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTotalActionPerformed

    private void jSizePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizePriceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSizePriceActionPerformed

    private void jSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizeActionPerformed
        // TODO add your handling code here:
        if (jSize.getSelectedIndex() == 1) {
            jSizePrice.setText("55");
        } else if (jSize.getSelectedIndex() == 2) {
            jSizePrice.setText("30");
        }
    }//GEN-LAST:event_jSizeActionPerformed

    private void jFlowerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFlowerTypeActionPerformed
        // TODO add your handling code here:
        switch (jFlowerType.getSelectedIndex()) {
            case 1:
                jFlowerPrice.setText("20");
                break;
            case 2:
                jFlowerPrice.setText("25");
                break;
            case 3:
                jFlowerPrice.setText("11");
                break;
            case 4:
                jFlowerPrice.setText("16");
                break;
            default:
                break;
        }

    }//GEN-LAST:event_jFlowerTypeActionPerformed

    private void jAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAccessoriesActionPerformed
        if (jAccessories.getSelectedIndex() == 1) {
            jAddOnPrice.setText("40");
        } else if (jAccessories.getSelectedIndex() == 2) {
            jAddOnPrice.setText("25");
        }
        calculateTotal();
    }//GEN-LAST:event_jAccessoriesActionPerformed

    private void jAddOnPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddOnPriceActionPerformed

    }//GEN-LAST:event_jAddOnPriceActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        jUpdate.setEnabled(false);
        try {
            TableModel model = jTable1.getModel();
            int index = jTable1.getSelectedRow();

            String flowerArrangementName = jStyle.getSelectedItem().toString();
            String ArrangementSize = jSize.getSelectedItem().toString();
            String flowertype = jFlowerType.getSelectedItem().toString();
            String accessories = jAccessories.getSelectedItem().toString();
            String priority = jPriority.getSelectedItem().toString();
            float price = Float.parseFloat(jTotal.getText());

            int customize_year = jCusDate.getCalendar().get(Calendar.YEAR);
            int customize_month = jCusDate.getCalendar().get(Calendar.MONTH);
            int customize_day = jCusDate.getCalendar().get(Calendar.DAY_OF_MONTH);

            Calendar customizeDate = Calendar.getInstance();
            customizeDate.set(Calendar.YEAR, customize_year);
            customizeDate.set(Calendar.MONTH, customize_month);
            customizeDate.set(Calendar.MONTH, customize_day);

            model.setValueAt(flowerArrangementName, index, 1);
            model.setValueAt(ArrangementSize, index, 2);
            model.setValueAt(flowertype, index, 3);
            model.setValueAt(accessories, index, 4);
            model.setValueAt(priority, index, 5);
            model.setValueAt(price, index, 6);
            model.setValueAt(customizeDate, index, 7);

            CustomizeLinkedList<CustomizeFlower> clist = null;
            while (!MainMenu.customizeList.isEmpty()) {
                CustomizeFlower c = MainMenu.customizeList.dequeue();

                Object[] data = {c.flowerArrangementName, c.ArrangementSize, c.flowertype, c.accessories,
                    c.price, c.priority, c.customizeDate};
                dm.addRow(data);
                clist.enqueue(c);
            }
            MainMenu.customizeList = clist;
            /* MainMenu.customizeList.get(index).flowerArrangementName = flowerArrangementName;
            MainMenu.customizeList.get(index).ArrangementSize = ArrangementSize;
            MainMenu.customizeList.get(index).flowertype = flowertype;
            MainMenu.customizeList.get(index).accessories = accessories;
            MainMenu.customizeList.get(index).priority = priority;
            MainMenu.customizeList.get(index).price = price;

             */
            JOptionPane.showMessageDialog(this, "Customer Details have been updated successfully.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Data input error", "Input Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customize.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customize().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jAccessories;
    private javax.swing.JButton jAddCustomize;
    private javax.swing.JTextField jAddOnPrice;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jCusDate;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jFlowerPrice;
    private javax.swing.JComboBox<String> jFlowerType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jPriority;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSize;
    private javax.swing.JTextField jSizePrice;
    private javax.swing.JComboBox<String> jStyle;
    private javax.swing.JTextField jSubTotal;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables

    private void loadDataIntoDDL() {
        jFlowerType.removeAllItems();
        jFlowerType.addItem(" ");

        for (Product product : MainMenu.prodList) {
            jFlowerType.addItem(product.getName());
        }

    }

    private String saveCustomizeIntoArray() {
        CustomizeFlower customize = null;
        try {
            String flowerArrangementName = jStyle.getSelectedItem().toString();
            String ArrangementSize = jSize.getSelectedItem().toString();
            String flowertype = jFlowerType.getSelectedItem().toString();
            String accessories = jAccessories.getSelectedItem().toString();
            String priority = jPriority.getSelectedItem().toString();
            float price = Float.parseFloat(jTotal.getText());
            int customize_year = jCusDate.getCalendar().get(Calendar.YEAR);
            int customize_month = jCusDate.getCalendar().get(Calendar.MONTH);
            int customize_day = jCusDate.getCalendar().get(Calendar.DAY_OF_MONTH);

            Calendar customizeDate = Calendar.getInstance();
            customizeDate.set(Calendar.YEAR, customize_year);
            customizeDate.set(Calendar.MONTH, customize_month);
            customizeDate.set(Calendar.MONTH, customize_day);

            customize = new CustomizeFlower(flowerArrangementName, ArrangementSize, flowertype, accessories, price, priority, customizeDate);

            MainMenu.customizeList.enqueue(customize);
            if (!MainMenu.customizeList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customize Order added");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Data input error", "Input Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
        return customize.id;

    }

    private void calculateSubTotal() {
        float currentTotal = Float.parseFloat(jTotal.getText());
        float subTotal = Float.parseFloat(jSubTotal.getText());
        subTotal += currentTotal;

        jSubTotal.setText(String.valueOf(subTotal));
    }

    private void calculateTotal() {
        float sizeprice = Float.parseFloat(jSizePrice.getText());
        float flowerprice = Float.parseFloat(jFlowerPrice.getText());
        float addOnprice = Float.parseFloat(jAddOnPrice.getText());

        String total = String.valueOf(sizeprice + flowerprice + addOnprice);
        jTotal.setText(total);
    }
}
