/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershopsystem;

/**
 *
 * @author scollex
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CatalogPanel = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblAmt = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jtfProdName = new javax.swing.JTextField();
        jtfAmt = new javax.swing.JTextField();
        jtfProdPrice = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        catalog_menu = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        catalog_menu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        catalog_menu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        catalog_menu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCategory.setFont(lblProdName.getFont());
        lblCategory.setText("Category");

        lblProdName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblProdName.setText("Product Name");

        lblAmt.setFont(lblProdName.getFont());
        lblAmt.setText("Amount");

        lblPrice.setFont(lblProdName.getFont());
        lblPrice.setText("Price");

        jtfProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdNameActionPerformed(evt);
            }
        });

        jtfAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAmtActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CatalogPanelLayout = new javax.swing.GroupLayout(CatalogPanel);
        CatalogPanel.setLayout(CatalogPanelLayout);
        CatalogPanelLayout.setHorizontalGroup(
            CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatalogPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProdName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lblAmt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        CatalogPanelLayout.setVerticalGroup(
            CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatalogPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CatalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(280, 50));

        catalog_menu.setText("Catalog");
        catalog_menu.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        catalog_menu.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem17.setFont(jMenuItem1.getFont());
        jMenuItem17.setText("View Catalog");
        catalog_menu.add(jMenuItem17);

        jMenuItem1.setFont(jMenuItem1.getFont());
        jMenuItem1.setText("Add new product");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        catalog_menu.add(jMenuItem1);

        jMenuItem2.setFont(jMenuItem1.getFont());
        jMenuItem2.setText("Update product");
        catalog_menu.add(jMenuItem2);

        jMenuItem3.setFont(jMenuItem1.getFont());
        jMenuItem3.setText("Delete product");
        catalog_menu.add(jMenuItem3);

        jMenuItem4.setFont(jMenuItem1.getFont());
        jMenuItem4.setText("Create New Category");
        catalog_menu.add(jMenuItem4);

        jMenuBar1.add(catalog_menu);

        catalog_menu1.setText("Sales");
        catalog_menu1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        catalog_menu1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem5.setFont(jMenuItem1.getFont());
        jMenuItem5.setText("Add new product");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        catalog_menu1.add(jMenuItem5);

        jMenuItem6.setFont(jMenuItem1.getFont());
        jMenuItem6.setText("Update product");
        catalog_menu1.add(jMenuItem6);

        jMenuItem7.setFont(jMenuItem1.getFont());
        jMenuItem7.setText("Delete product");
        catalog_menu1.add(jMenuItem7);

        jMenuItem8.setFont(jMenuItem1.getFont());
        jMenuItem8.setText("Create New Category");
        catalog_menu1.add(jMenuItem8);

        jMenuBar1.add(catalog_menu1);

        catalog_menu2.setText("Delivery");
        catalog_menu2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        catalog_menu2.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem9.setFont(jMenuItem1.getFont());
        jMenuItem9.setText("Add new product");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        catalog_menu2.add(jMenuItem9);

        jMenuItem10.setFont(jMenuItem1.getFont());
        jMenuItem10.setText("Update product");
        catalog_menu2.add(jMenuItem10);

        jMenuItem11.setFont(jMenuItem1.getFont());
        jMenuItem11.setText("Delete product");
        catalog_menu2.add(jMenuItem11);

        jMenuItem12.setFont(jMenuItem1.getFont());
        jMenuItem12.setText("Create New Category");
        catalog_menu2.add(jMenuItem12);

        jMenuBar1.add(catalog_menu2);

        catalog_menu3.setText("Customer");
        catalog_menu3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        catalog_menu3.setMargin(new java.awt.Insets(10, 10, 10, 10));

        jMenuItem13.setFont(jMenuItem1.getFont());
        jMenuItem13.setText("Add new product");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        catalog_menu3.add(jMenuItem13);

        jMenuItem14.setFont(jMenuItem1.getFont());
        jMenuItem14.setText("Update product");
        catalog_menu3.add(jMenuItem14);

        jMenuItem15.setFont(jMenuItem1.getFont());
        jMenuItem15.setText("Delete product");
        catalog_menu3.add(jMenuItem15);

        jMenuItem16.setFont(jMenuItem1.getFont());
        jMenuItem16.setText("Create New Category");
        catalog_menu3.add(jMenuItem16);

        jMenuBar1.add(catalog_menu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CatalogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CatalogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.CatalogPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jtfAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAmtActionPerformed

    private void jtfProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenu frame = new MainMenu();
                frame.setVisible(true);
                frame.CatalogPanel.setVisible(false);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CatalogPanel;
    private javax.swing.JMenu catalog_menu;
    private javax.swing.JMenu catalog_menu1;
    private javax.swing.JMenu catalog_menu2;
    private javax.swing.JMenu catalog_menu3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTextField jtfAmt;
    private javax.swing.JTextField jtfProdName;
    private javax.swing.JTextField jtfProdPrice;
    private javax.swing.JLabel lblAmt;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProdName;
    // End of variables declaration//GEN-END:variables
}
