/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershopsystem;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author scollex
 */
public class PickupMenu extends javax.swing.JFrame {

    /**
     * Creates new form PickupMenu
     */
    public PickupMenu() {
        initComponents();
        loadDataIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDate.setText("Product pick up list");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Customer", "Status", "Coming at", "Collected at"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        String ordid = (String) jTable1.getModel().getValueAt(index, 1);
        String custName = (String) jTable1.getModel().getValueAt(index, 2);
        String status = (String) jTable1.getModel().getValueAt(index, 3);
        String collectTime = (String) jTable1.getModel().getValueAt(index, 4);
        PickupConfirm confirm = new PickupConfirm(Integer.parseInt(ordid));
        try {
            confirm.main(null);
            confirm.lblOrderID.setText(ordid);
            confirm.lblCustomer.setText(custName);
            if (status.equalsIgnoreCase("Collected")) {
                confirm.btnCollect.setVisible(false);
                confirm.btnCancel.setVisible(true);
                confirm.lblCollectedTime.setText(collectTime);
            } else {
                confirm.btnCollect.setVisible(true);
                confirm.btnCancel.setVisible(false);
                confirm.lblCollectedTime.setText("Not collected yet");
            }
        } catch (Exception ex) {

        }


    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickupMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDate;
    // End of variables declaration//GEN-END:variables

    private void loadDataIntoTable() {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        //clear all record in table
        dm.setRowCount(0);

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        //load data into table from list
        for (int i = 0; i < MainMenu.deliveryList.size(); i++) {
            if (MainMenu.deliveryList.get(i).method.equalsIgnoreCase("Pick Up")
                    && MainMenu.deliveryList.get(i).status.equalsIgnoreCase("pending")) {
                Object[] data = new Object[5];
                data[0] = MainMenu.deliveryList.get(i).getOrder().orderid;
                data[1] = MainMenu.deliveryList.get(i).getCust().name;
                data[2] = MainMenu.deliveryList.get(i).status;
                data[3] = format.format(MainMenu.deliveryList.get(i).getDate_of_deliver().getTime());
                if (MainMenu.deliveryList.get(i).getDate_of_collect() != null) {
                    data[4] = format.format(MainMenu.deliveryList.get(i).getDate_of_collect().getTime());
                } else {
                    data[4] = " - ";
                }
                dm.addRow(data);
            }
        }
        if (dm.getRowCount()
                == 0) {
            JOptionPane.showMessageDialog(this, "No pick up record");
        }
        //Set the width for each column
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
        
        jTable1.setModel(dm);
    }
}
